"""empty message

Revision ID: 69d294790ff5
Revises: 6fdd341bf52c
Create Date: 2020-05-16 23:13:47.830604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d294790ff5'
down_revision = '6fdd341bf52c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'city1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('city1', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
